### PR TITLE
chore: fix autoprefixer, fixes preboot/angular-webpack#40

### PR DESCRIPTION
**Pull request by phra**

### CODE REVIEW

**Comment by phra** [comment]
@Foxandxss feel free to merge the PR.

**Comment by Foxandxss** [comment]
Does this really fix it? It should pick the loaders in the other way. I will test.

**Comment by phra** [comment]
i followed the loaders docs, it seems to be working to me.
let me know if it's not working for you. (i tested w/ 'last 20 version' and random css animation rule)

**Comment by Foxandxss** [comment]
Will try tomorrow, really late here.

**Comment by phra** [comment]
PS: it would be nice to add precss plugin to postcss. what do you think about it?
i'm in italy atm so same timezone. ;)

**Comment by Foxandxss** [comment]
Never heard of it, will check.

**Comment by phra** [comment]
basically it lets you to use SASS syntax in your css without including node-sass or ruby-sass.

**Comment by phra** [comment]
@Foxandxss can i merge this PR?

**Comment by Foxandxss** [comment]
Sure.

**Comment by phra** [comment]
done!

**Pull request merged**
