### PR TITLE
Generate relative script urls

### PR DESCRIPTION
**Pull request by mohammedpascal**
npm run build generates urls with leading slash

The app doesn't work when it runs on subdirectory for instance http://localhost/angular2-webpack/dist
because it looks for scripts under http://localhost/js/app/.. instead of http://localhost/angular2-webpack/dist/js/app/...

### CODE REVIEW

**Comment by ocombe** [comment]
It looks good to me, @Foxandxss ?

**Comment by Foxandxss** [comment]
I guess. I wouldn't ever run an application from a subdirectory, I would run the server on that directory.

**Comment by mohammedpascal** [comment]
Sometimes I share projects with my clients by uploading them to my website under sub-directories

**Comment by GaryB432** [comment]
I have been running from subfolders on my old-school windows hosting provider for a long time with this awesome starter, having set my publicPath to '' (not dot)

**Pull request closed without merging**
