### PR TITLE
refactor: split webpack.config to 3 files based on ENV

### PR DESCRIPTION
**Pull request by rantrix**
How about we split the `webpack.config.js` file into three based on the `ENV`?
- `webpack.prod.config.js`
- `webpack.dev.config.js`
- `webpack.test.config.js`

Reading the ternary operator inside the config file can get pretty hairy. Splitting the file into three based on `ENV` can offer a lot more configuration and can be easier to spot issues.

Downside is that if the config needs changing, it will have to be configured for all three environments. A bit more overhead for readability.

What do you think?

Feel free to close this PR if this issue has already been decided in the past 😃 . I did a quick search of the PR history and issues and couldn't find previous discussions on this topic.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Seems like --env param from webpack is going to be backported to Webpack 1, so when that happens, we could consider the split in a better way.

**Comment by rantrix** [comment]
@Foxandxss Can you elaborate please? I'm ready to take in your wisdom =)

**Comment by Foxandxss** [comment]
So webpack 2 has an option like `--dev=prod` so in the config instead of an object you have a function like:

```
module.exports = function(env) {
  // env contains prod or dev or test or whatever
}
```

Is a really useful feature that seems that will come to Webpack 1 as well.

**Comment by rantrix** [comment]
Ohhh, that's pretty neat and it seems like we'll still need to do ternary operators.

```
module.exports = function(env) {
  // env contains prod or dev or test or whatever
  let isTest = env === 'test';
  let isDev = env === 'dev';
  let isProd = env === 'prod';

  ...
  ...
  loaders: [
    {
      test: /\.ts$/,
      loaders: ['ts', 'angular2-template-loader'],
      exclude: [isTest ? /\.(e2e)\.ts$/ : /\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/]
      exclude: [/\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/]
    },
  ...
  ...
}
```

Yeah? I guess we'll wait and see

**Comment by Foxandxss** [comment]
Yes, but right now I have a npm event name that can get a lot of different values and I just need three.

For example, I cannot make `karma start` to work because when it gets into the config, there is no ENV set, but with --env I can make that work if needed.

**Comment by rantrix** [comment]
Hum. Looks like you might know better. Does this not work? Just curious

```
// karma.conf.js

var webpackConfig = require('./webpack.test.config') // <== require the test config one

module.exports = function (config) {
  ...
  preprocessors: {
    './karma-shim.js': ['webpack', 'sourcemap']
  },
  webpack: webpackConfig, // <== in it goes
  ...
};
```

```
// webpack.test.config.js

const ENV = process.env.ENV || 'TEST'; // <== default to 'TEST' or grab it from when the command is executed

module.exports = function makeWebpackConfig() {
  ...
};
```

```
/// package.json

"scripts": {
  "server": "webpack-dev-server --config=webpack.dev.config.js --inline --progress --port 8080 && npm run _open:chrome 'http://localhost:8080'",
  "start": "npm run server",
  "test": "karma start"
}
```

Then you just run `npm run test`. If you want to specify an `env`, you can `ENV=test npm run test`.

**Comment by Foxandxss** [comment]
If you split like that, yes, you can do that.

Problem is, I am not sold on the split and the --env thing would be to fix it on a single file.

**Comment by ollwenjones** [comment]
Depending on how different your configs end up, it makes sense to split them. When I originally started with the AngularClass ng2 seed (like... December), the three files were 90% the same, and that just seemed like a maintenance nightmare to me. The single file approach seems a lot more maintainable to me, and the ternary operators being hairy to read is sort of a subjective reason to split things. Ternary opertarors / switches, etc. also make it explicit to read the config differences between the --env, versus having to compare different files if you need to compare them.

On the React side, I have seen some configs that broke parts of the config into different files that got pulled together based on the --env, which seemed pretty elegant/maintainable, but takes more perusing to understand.

**Comment by tb** [comment]
I also like single file, but after I recently saw [webpack-merge](https://www.npmjs.com/package/webpack-merge) in action (i.e. in [angualr2-mdl-ext](https://github.com/mseemann/angular2-mdl-ext/blob/master/config/webpack/webpack.dev.js) ) Multifile setup looks more appealing too me.

**Comment by Foxandxss** [comment]
I am closing this but I am going to do something like this in a new branch.

**Comment by tb** [comment]
@Foxandxss BTW Current setup can be improved with https://www.npmjs.com/package/webpack-config-utils

**Comment by Foxandxss** [comment]
Definitely @tb. But I grew tired of so many checks in one file. It is sometimes hard to see whether something is for prod only, not for test or what.

**Pull request closed without merging**
