### PR TITLE
Fixes #51 - Replace isparta-loader with babel-plugin-istanbul

### LINKED ISSUE #51: isparta-loader is deprecated, replace with babel-plugin-istanbul?
As from isparta-loader's readme, it is deprecated in favor of babel-plugin-istanbul.
I've made this change in my own project but I'm not sure I've done it correctly.
I can make a pr but I need an help to be sure it is all correct.

### PR DESCRIPTION
**Pull request by McGiogen**
Fixes #51 .

### CODE REVIEW

**Comment by matthamil** [comment]
I get the following error when trying to run your PR locally:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/matthamil/.nvm/versions/node/v6.4.0/bin/node" "/Users/matthamil/.nvm/versions/node/v6.4.0/bin/npm" "run" "test"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular-webpack-workflow@1.0.0 test: `cross-env NODE_ENV=test karma start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular-webpack-workflow@1.0.0 test script 'cross-env NODE_ENV=test karma start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-webpack-workflow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=test karma start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-webpack-workflow
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-webpack-workflow
npm ERR! There is likely additional logging output above.

```

Trying to use this repo to get testing configured with an Angular 1.x and Webpack project.

**Comment by McGiogen** [comment]
Are you using Windows? I've deleted all my global npm packages, cloned my repo and reinstalled all npm packages to have a clean environment and it's working like a charm. But I'm on linux, Xubuntu 16.04.

**Comment by matthamil** [comment]
Somehow I managed to clone it down incorrectly. It works fine now. I'm running OSX El Capitan.

**Comment by phra** [comment]
i'm closing this in favor of #53

**Pull request closed without merging**
