### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by phra**
simple maintenance.

### CODE REVIEW

**Comment by Foxandxss** [comment]
I appreciate the PR but I am not sure I want that jsconfig (which won't work because has comments) and not sure if I want typings for this project.

**Comment by phra** [comment]
i've fixed the jsconfig.json file that was created by vscode and added typings.json config for intellisense.
feel free to merge or close this PR.

cheers.

**Comment by Foxandxss** [comment]
I will accept a PR where dependencies are updated but not the typings nor the jsconfig. That can be added for you locally for your project.

**Comment by phra** [comment]
as you prefer, done.

**Comment by Foxandxss** [comment]
Also not that npm-check, sorry.

**Comment by phra** [comment]
i've stripped away npm-check. (btw what's wrong with that?)

**Comment by Foxandxss** [comment]
npm-check is better installed globally so you can `npm-check` any project of yours. Better than having to install it by hand to every project.

**Comment by phra** [comment]
i'm against to global deps. (what if i have two project with different semver compatibility of a certain tool/library?)

i prefer the $PATH approach, i.e.
```bash
 $ export $PATH=$PATH:./node_modules/.bin
```
 and install everything locally.

**Comment by Foxandxss** [comment]
I agree on that, but is not the case of this tool.

**Pull request merged**
