### PR TITLE
add component template

### PR DESCRIPTION
**Pull request by phra**
it would be nice that we can auto-scaffold components via CLI commands. this commit is a backport from [@AngularClass/NG6-starter code](https://github.com/AngularClass/NG6-starter). (MIT license too)

### CODE REVIEW

**Comment by Foxandxss** [comment]
I don't really like generators to be honest. I will think about it.

**Comment by phra** [comment]
it's very useful imho.
let me know if i have to make some changes.

**Comment by fabiobiondi** [comment]
+1

**Comment by Foxandxss** [comment]
This won't go in, sorry.

**Comment by Foxandxss** [comment]
Please @phra don't start closing issues redirecting to here. I understand you want this, but making pressure like that won't work :)

**Comment by phra** [comment]
no need to merge this PR, just showing to people how to declare components with working tests.

**Pull request closed without merging**
