### PR TITLE
explicitly include all source code, fixes #8

### LINKED ISSUE #8: Check coverage when a directory has no tests
Seems like having directories without tests makes the plugin ignore it.

### PR DESCRIPTION
**Pull request by phra**

### CODE REVIEW

**Comment by Foxandxss** [comment]
I am not able to reproduce the error anymore. I just put a new `src/app/home` folder without tests and is getting covered...

**Comment by Foxandxss** [comment]
I can now, but better if instead of starting at root `.` we put it at `./app`.

**Comment by phra** [comment]
ok, that's fine for me. i'll update the PR accordingly. :+1:

**Comment by phra** [comment]
@Foxandxss can we merge this PR now?

**Pull request merged**
