### PR TITLE
Fixes #34 - adding sass

### LINKED ISSUE #34: What is the simplest, most straightforward manner of including CSS preprocessor?
Some reading: http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/

screen shot 2016-06-23 at 22 43 54

Having a look at the list of features:
screen shot 2016-06-23 at 22 44 22

Having look at the source code: https://github.com/preboot/angular-webpack/blob/master/webpack.config.js#L97-L102

---

I put a `test.scss` file into `style` directory and the styles wasn't applied.

```
body {
  a {
    color: red;
  }
}
```

My experience with WebPack so far - it combines all `.js` into a single `app.bundle.js` - I would like to have same feature for the styles... Before I start reinventing the wheel - is it a matter of changing some settings in CSS loader, or maybe adding some other loader such as: https://github.com/jtangelder/sass-loader ?

Or maybe it is working all the time, it's just me not naming files correctly, not importing them?

---

I can confirm that `test.css` is working just fine while `.scss` fails to load:
screen shot 2016-06-23 at 22 55 05

### PR DESCRIPTION
**Pull request by stefek99**

### CODE REVIEW

**Comment by stefek99** [comment]
Apparently commit messages #34 are linked to issues, pull request are not.

But yeah: https://github.com/preboot/angular-webpack/issues/34

**Comment by Foxandxss** [comment]
I like the idea but it should be done differently. Like we do at angular2-webpack repo (same organization).

**Comment by stefek99** [comment]
Having a look as we speak: https://github.com/preboot/angular2-webpack/blob/master/webpack.config.js

**Comment by phra** [comment]
yeah, drop node-sass in favor of postcss. @stefek99 are you working on this?

**Comment by stefek99** [comment]
@phra Not really working on this :smiling_imp: 1000s of other priorities... I had a chat with the mantainer of the repo - he is busy - I'm busy - this guy is busy too - http://www.michaelbromley.co.uk/blog/529/why-i-havent-fixed-your-issue-yet

**Comment by phra** [comment]
if i have spare time i'll work on this. it's easy, look at [USAGE](https://github.com/postcss/postcss-loader) of postcss-loader. ( [precss](https://github.com/jonathantneal/precss) is for using scss syntax with postcss)

**Comment by phra** [comment]
@stefek99 do you have worked on this? otherwise i have to reject this.

**Comment by stefek99** [comment]
Nope.

**Comment by phra** [comment]
i'm closing this.

**Pull request closed without merging**
