### PR TITLE
add browsersync support, fixes #180

### LINKED ISSUE #180: add browsersync plugin to webpack-dev-server
hi,

it would be nice to add this plugin https://github.com/Va1/browser-sync-webpack-plugin to get browsersync features along with `webpack-dev-server` ones.

i've already implemented in another project and it's working well.
what do you think guys?
i can do this maybe the next week.
cheers.

### PR DESCRIPTION
**Pull request by phra**

### CODE REVIEW

**Comment by hijoncon** [comment]
Looks good :)

**Comment by Foxandxss** [comment]
And why I want this?

**Comment by phra** [comment]
because it's cool having browsersync! :100:

**Comment by Foxandxss** [comment]
I want to leave the starter to be minimal. Not adding features just because they are cool.

**Comment by phra** [comment]
browsersync is just awesome for live cross-testing, that's not an opinion. do what you think it's better.

**Comment by biapar** [comment]
+1

**Comment by GaryB432** [comment]
doesn't the hot module replacement already in place provide the same "awesome" functionality?

**Comment by phra** [comment]
@GaryB432 nope, they are two different things.

**Pull request closed without merging**
